name: MERN Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # # 2️⃣ Setup Node.js
      # - name: Setup Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
      #     cache-dependency-path: |
      #       client/package-lock.json
      #       server/package-lock.json

      # ---------------- BACKEND ----------------
      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Build backend
        working-directory: server
        run: npm run build --if-present

      - name: Test backend
        working-directory: server
        run: npm test --if-present

      # ---------------- FRONTEND ----------------
      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Test frontend
        working-directory: client
        run: npm test --if-present
